package ui.core.handlers;

import java.io.File;
import java.io.IOException;
import javafx.scene.image.WritableImage;
import models.atomic.Constants;
import ui.Ui;
import ui.core.graph.automata.AutomataVisualizer;
import ui.core.graph.tree.InteractiveTreeView;
import ui.core.services.FileService;
import ui.core.state.AnalysisState;
import ui.core.tables.FirstFollowTableManager;
import ui.core.tables.ParserTableManager;
import ui.core.tables.SymbolTableManager;
import ui.util.UiUtils;

/**
 * Handles exporting various analysis artifacts to files.
 *
 * <p>This handler provides comprehensive export capabilities for all analysis results generated by
 * the application:
 *
 * <ul>
 *   <li><b>Images:</b> Automaton diagrams, grammar trees, parse trees
 *   <li><b>Text Data:</b> Graphviz DOT format, console logs, output logs
 *   <li><b>Tabular Data:</b> Symbol tables, FIRST/FOLLOW sets, parse tables as CSV
 *   <li><b>Reports:</b> Combined reports merging multiple log sources
 * </ul>
 *
 * <p>All export operations are user-interactive, showing file chooser dialogs and providing
 * feedback in the output area. Files are saved with timestamped names to prevent overwriting.
 *
 * <p>Typical usage:
 *
 * <pre>
 * ExportHandler exporter = new ExportHandler(ui, state);
 *
 * // Export the automaton visualization
 * exporter.handleExportGraphImage();
 *
 * // Export analysis tables as CSV
 * exporter.handleExportCSV();
 *
 * // Generate a full report
 * exporter.handleGenerateFullReport();
 * </pre>
 *
 * @see Ui
 * @see AnalysisState
 * @see FileService
 */
public class ExportHandler {
    private final Ui ui;
    private final AnalysisState state;

    /**
     * Constructs an ExportHandler with references to the main UI and analysis state.
     *
     * @param ui the main UI instance providing access to visual components
     * @param state the shared analysis state for checking data availability
     */
    public ExportHandler(Ui ui, AnalysisState state) {
        this.ui = ui;
        this.state = state;
    }

    /**
     * Exports the current DFA automaton as a PNG image using Graphviz.
     *
     * <p>The automaton visualization is generated using Graphviz and saved as a PNG file with a
     * timestamped filename in the output folder.
     *
     * <p>Requires that an automaton has been built (i.e., token rules loaded). If no automaton
     * exists, the method returns silently without action.
     */
    public void handleExportGraphImage() {
        if (state.getCurrentAutomaton() == null) return;
        try {
            String fileName =
                    UiUtils.timestampFileName(Constants.OUTPUT_FOLDER + "automata", "png", true);
            AutomataVisualizer.exportToImage(state.getCurrentAutomaton(), fileName);
            ui.getOutputArea().setText("Automata image exported natively as: " + fileName);
        } catch (Exception e) {
            ui.getOutputArea().setText("Export failed: " + e.getMessage());
        }
    }

    /**
     * Exports the grammar tree visualization as a PNG image.
     *
     * <p>Captures a snapshot of the currently displayed grammar tree and saves it to a file
     * selected by the user.
     *
     * <p>Requires that a grammar tree has been generated and displayed ({@code hasGrammarTree} is
     * {@code true}).
     */
    public void handleExportGrammarTreeImage() {
        if (!state.isHasGrammarTree()) return;
        exportTreeSnapshot(
                (InteractiveTreeView) ui.getGrammarTreeContainer().getCenter(), "grammar_tree");
    }

    /**
     * Exports the parse tree of the last successfully parsed input as a PNG image.
     *
     * <p>Captures a snapshot of the currently displayed input parse tree and saves it to a file
     * selected by the user.
     *
     * <p>Requires that an input tree has been generated and displayed ({@code hasInputTree} is
     * {@code true}).
     */
    public void handleExportInputTreeImage() {
        if (!state.isHasInputTree()) return;
        exportTreeSnapshot(
                (InteractiveTreeView) ui.getInputTreeContainer().getCenter(), "input_tree");
    }

    /**
     * Exports an interactive tree view to a PNG file via a save dialog.
     *
     * @param view the tree view to export (must be an InteractiveTreeView)
     * @param baseName the base name for the suggested file (without folder or extension)
     */
    private void exportTreeSnapshot(InteractiveTreeView view, String baseName) {
        try {
            String fullPath = Constants.OUTPUT_FOLDER + baseName + ".png";
            File file =
                    FileService.saveStringToFile(
                            ui.getInputArea().getScene().getWindow(), "", fullPath, "*.png");
            if (file != null) {
                WritableImage snapshot = view.generateSnapshot();
                UiUtils.saveSnapshot(snapshot, file);
                ui.getOutputArea().setText("Tree exported successfully to " + file.getName());
            }
        } catch (IOException e) {
            ui.getOutputArea().setText("Export failed: " + e.getMessage());
        }
    }

    /**
     * Exports the symbol table, FIRST/FOLLOW sets, and parse table as CSV files.
     *
     * <p>This method exports all available tabular data to CSV format:
     *
     * <ul>
     *   <li>Symbol table → {@code symbol_table.csv}
     *   <li>FIRST/FOLLOW sets → {@code first_follow.csv}
     *   <li>Parse table → {@code parse_table.csv}
     * </ul>
     *
     * <p>Each CSV file is saved in the output folder. Only tables with available data are exported
     * (based on state flags).
     *
     * @throws IOException if any file write operation fails (errors are caught and displayed)
     */
    public void handleExportCSV() {
        String outputFolder = Constants.OUTPUT_FOLDER;
        try {
            if (state.isHasSymbolTableData()) {
                SymbolTableManager.exportSymbolTableCsv(
                        outputFolder + "symbol_table.csv", ui.getSymbolTableViewer());
            }
            if (state.isHasFirstFollowData()) {
                FirstFollowTableManager.exportFirstFollowCsv(
                        outputFolder + "first_follow.csv",
                        state.getCurrentFirstFollowTable(),
                        ui.getFirstFollowTable());
            }
            if (state.isHasParseTableData()) {
                ParserTableManager.exportParseTableCsv(
                        outputFolder + "parse_table.csv",
                        state.getCurrentParseTable(),
                        ui.getParserTable());
            }
            ui.getOutputArea().setText("Tables successfully exported to CSVs in " + outputFolder);
        } catch (IOException e) {
            ui.getOutputArea().setText("CSV Export failed: " + e.getMessage());
        }
    }

    /**
     * Exports the Graphviz DOT representation of the current DFA to a text file.
     *
     * <p>The DOT format is a plain text graph description language that can be processed by
     * Graphviz tools for further customization or rendering.
     *
     * <p>Requires that an automaton has been built. The user is prompted to select a save location.
     */
    public void handleExportGraphText() {
        if (state.getCurrentAutomaton() == null) return;
        try {
            String dotFormat = AutomataVisualizer.generateDotFormat(state.getCurrentAutomaton());
            File file =
                    FileService.saveStringToFile(
                            ui.getInputArea().getScene().getWindow(),
                            dotFormat,
                            Constants.OUTPUT_FOLDER + "automata.dot",
                            "*.dot",
                            "*.txt");
            if (file != null) {
                ui.getOutputArea().setText("Graph definition exported to " + file.getName());
            }
        } catch (IOException e) {
            ui.getOutputArea().setText("Export failed: " + e.getMessage());
        }
    }

    /**
     * Saves the contents of the console log area to a text file.
     *
     * <p>Prompts the user to select a save location and writes the console log content to a text
     * file.
     */
    public void handleSaveConsoleLog() {
        saveTextArea(ui.getConsoleArea(), "console_log", "*.txt");
    }

    /**
     * Saves the contents of the output area to a text file.
     *
     * <p>Prompts the user to select a save location and writes the output area content to a text
     * file.
     */
    public void handleSaveOutput() {
        saveTextArea(ui.getOutputArea(), "output_log", "*.txt");
    }

    /**
     * Saves the contents of the validation output area to a text file.
     *
     * <p>Prompts the user to select a save location and writes the validation results to a text
     * file.
     */
    public void handleSaveValidation() {
        saveTextArea(ui.getValidatorOutputArea(), "validation_report", "*.txt");
    }

    /**
     * Saves a TextArea's content to a file via a save dialog.
     *
     * @param area the TextArea to save (must not be null)
     * @param baseName the base name for the file (without folder or extension)
     * @param extension the file extension filter (e.g., "*.txt")
     */
    private void saveTextArea(
            javafx.scene.control.TextArea area, String baseName, String extension) {
        try {
            String fullPath = Constants.OUTPUT_FOLDER + baseName + ".txt";
            File file =
                    FileService.saveStringToFile(
                            area.getScene().getWindow(), area.getText(), fullPath, extension);
            if (file != null) {
                ui.getOutputArea().setText(baseName + " saved to " + file.getName());
            }
        } catch (IOException e) {
            ui.getOutputArea().setText("Save failed: " + e.getMessage());
        }
    }

    /**
     * Generates a comprehensive report combining output log, console log, and validation results.
     *
     * <p>The report includes:
     *
     * <ul>
     *   <li>A header with report metadata
     *   <li>The output log content (lexer/parser results)
     *   <li>The console log content (background task messages)
     *   <li>Grammar validation results (if available)
     * </ul>
     *
     * <p>Prompts the user to save the report as a text file. This is useful for documenting the
     * complete compiler execution session.
     */
    public void handleGenerateFullReport() {
        try {
            StringBuilder report = new StringBuilder();
            report.append("=== COMPILER REPORT ===\n\n");
            report.append("--- Output Log ---\n")
                    .append(ui.getOutputArea().getText())
                    .append("\n\n");
            report.append("--- Console Log ---\n")
                    .append(ui.getConsoleArea().getText())
                    .append("\n\n");
            if (state.isHasValidationData()) {
                report.append("--- Grammar Validation ---\n")
                        .append(ui.getValidatorOutputArea().getText())
                        .append("\n\n");
            }
            FileService.saveStringToFile(
                    ui.getInputArea().getScene().getWindow(),
                    report.toString(),
                    Constants.OUTPUT_FOLDER + "full_report.txt",
                    "*.txt");
            ui.getOutputArea().setText("Full report generated in " + Constants.OUTPUT_FOLDER);
        } catch (IOException e) {
            ui.getOutputArea().setText("Report generation failed: " + e.getMessage());
        }
    }
}
